### PR TITLE
Add `--no-optional-locks` to `git status` command

### PR DESCRIPTION
**Pull request by feddischson**
I came across this issue in combination with `tpope/vim-fugitive` as described here: https://github.com/tpope/vim-fugitive/issues/1624#

### CODE REVIEW

**Comment by Xuyuanp** [comment]
Thanks!

**Comment by sagiegurari** [comment]
This causes endless errors since my git does not support this flag. 
I can't upgrade my git to a version that supports it (i tried using apt-get to latest today).

**Comment by Xuyuanp** [comment]
@sagiegurari @feddischson I pushed a new PR #176.
Does it solve your problem?

**Comment by sagiegurari** [comment]
looking at the code, i think it should fix it. thanks

**Comment by feddischson** [comment]
@Xuyuanp also works in my case, thanks

**Comment by Xuyuanp** [comment]
merged

**Pull request merged**
