### PR TITLE
Merge in @robinfehr's fork into the current master

### PR DESCRIPTION
**Pull request by Aldlevine**
_The original intent of my fork was to fix this issue, but it evolved. See next comment_

This wasn't working for me if the root path contains a space. This fixes the issue by wrapping the path in the system command in double-quotes. Works beautifully for me now.

### CODE REVIEW

**Comment by Aldlevine** [comment]
I've just spent some time on this to bring @robinfehr's fork up to date (mainly because I need ignored files/dirs to be highlighted as well).

Example image of a portion of my dotfile repo:
image

**Comment by virus-found** [comment]
Any chance it is merged into the main branch?

**Comment by mxstbr** [comment]
How do I enable this? I tried installing your fork and then setting these options I found reading through your code:

```vim
let g:NERDTreeGitStatusWithFlags=0
let g:NERDTreeGitStatusNodeColorization=1
```

But it doesn't work :confused:

screen shot 2017-08-31 at 12 05 50 pm

Any hints what I could be doing wrong?

**Comment by virus-found** [comment]
@mxstbr 
no idea what `let g:NERDTreeGitStatusWithFlags=0` is, there is no such word in my whole ~/.vim/
`let g:NERDTreeGitStatusNodeColorization=1` should be enough

The only hint I can give - `cd` to your git root project dir
And nerdtree's root should be the same dir

I have issues if I change either of those

**Comment by mxstbr** [comment]
Removing `let g:NERDTreeGitStatusWithFlags=0` worked! I wanted to avoid having the `[x]` in the sidebar as well as a color change, I only want the color change, but that works too. Awesome, thanks!

**Comment by Aldlevine** [comment]
If you're curious, these are the setting I'm using to acheive the what's in my screenshot:

```vim
" NERDTree Git
let g:NERDTreeShowIgnoredStatus = 1  "enables ignored highlighting
let g:NERDTreeGitStatusNodeColorization = 1  "enables colorization
let g:NERDTreeGitStatusWithFlags = 1  "enables flags, (may be default), required for colorization

highlight link NERDTreeDir Question  "custom color
highlight link NERDTreeGitStatusIgnored Comment  "custom color
highlight link NERDTreeGitStatusModified cssURL  "custom color

" NERDTree
set hidden
let g:NERDTreeDirArrowExpandable = nr2char(8200)  "sets expandable character
let g:NERDTreeDirArrowCollapsible = nr2char(8200)  "sets collapsible character
let g:WebDevIconsNerdTreeAfterGlyphPadding = ''  "removes padding after devicon glyph
let g:WebDevIconsUnicodeDecorateFolderNodes = 1  "enables decorating folder nodes

autocmd FileType nerdtree setlocal nolist  "if you show hidden characters, this hides them in NERDTree
```

I can look into updating this to fix hiding the status indicators (which is intended functionality). I have some ideas about what's wrong, so I'll hopefully have a solution soon.

**Comment by virus-found** [comment]
As far as I know, nobody invented the functionality to disable icons and use only node colour?

**Comment by robinfehr** [comment]
nice to see my pull request evolving. it won't be merged though (I assume) until we enable the switch to the "non atom" kind of mode. have a look at the discussion of the original PR. I'm using my own fork since then - I was just too busy and yeah lack of motivation to complete that was an issue as well ;)

**Comment by cronokun** [comment]
Any ideas why it's not working in MacVim?

**Comment by mhartington** [comment]
Has this PR gone stale? Or would you accept a refreshed PR?

**Comment by Xuyuanp** [comment]
I merged most features except color highlighting, because the code has been changed a lot since this pr, it's really a mess to resolve conflicts.
I'm going to add color highlighting back in the future, and new PRs base on the current main branch are welcome

**Pull request merged**
