### PR TITLE
Add 'Ignored' status

### PR DESCRIPTION
**Pull request by runoshun**
I added 'Ignored' status using '--ignored' flag.

### CODE REVIEW

**Comment by poberherr** [comment]
I was looking exactly for that
LGTM

**Comment by ismay** [comment]
Any progress on this? I wouldn't mind helping to get this merged, anything I can do?

**Comment by poberherr** [comment]
resolved the conflict here but can also change it here

https://github.com/Xuyuanp/nerdtree-git-plugin/pull/64

I think the maintainer is just inactive

**Comment by ismay** [comment]
Ah ok. @Xuyuanp can we help with anything? Would be nice to get this merged and #64 is ready to go.

**Comment by poberherr** [comment]
Thanks

**Comment by ismay** [comment]
Thanks @Xuyuanp

**Comment by Xuyuanp** [comment]
As this feature may cost more time (#76), I disable it by default. If you want to enable it again, please set `g:NERDTreeShowIgnoredStatus` to 1 in vimrc.

See more details in 76cd21b1259d2242edce3d62247d0b7b5c77e33e

**Pull request merged**
