### PR TITLE
Excluded hard coded syntax highlighting

### PR DESCRIPTION
**Pull request by PickRelated**
This allows user to change symbols
Readme now also includes info about symbols variable

### CODE REVIEW

**Comment by Xuyuanp** [comment]
Hi, I pushed some changes to develop branch, could you please help me review it?

**Comment by PickRelated** [comment]
Sure! Give me a sec.

**Comment by PickRelated** [comment]
That looks much better then what I've done. I am not good at vim script, but if assigning `~ or _ or +` to one of symbols does not cast error on opening NERDTree, you have done everything right! 

I have to go now, but if you want - I can checkout developer branch and test it ~ 5 hours later.

**Comment by Xuyuanp** [comment]
Feel free to do it!
And don't forget to add your self to Credits in README, you deserve it. LOL

**Comment by PickRelated** [comment]
I've tested it and it works perfect! Which gives me an idea for NERDTree plugin. I have forked it and made the same mistake. With your approach I will be able to avoid regex escaping bugs there too. Thanks!

Now I would say you can merge develop into master but do not forget to remove **Note** section from readme because we do not need one any more :)

I am going to an interview right now. It would be awesome if you would add me to credits section in readme because I can not do it myself. That would be too boldly of me. LOL. If you spoke seriously, of cause. This way I could give my employer link to your plugin and get a good credit out of it.

**Comment by Xuyuanp** [comment]
All right!

I have merged develop into master and updated README.

Good Luck!

**Comment by PickRelated** [comment]
Oh, thanks, man! I appreciate it! ` Add custom indicators & Review code` sounds like I have made a huge countibution :laughing:

**Pull request merged**
